### ISSUE TITLE
feat: Add warp in the integration test suite to benchmark perf

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#576]
# Feature Request

**Describe the Feature Request**

Add [`warp` ](https://nethermindeth.github.io/warp/) to the solidity based tests to test against warped contracts. This would allow us to benchmark kakarot VS warp resources usage and soundness.

**Describe Preferred Solution**

Add warp step before the test runs (in the `build-sol`) stage.
Tweak the `solidity_fixture` to be able to toggle the target between the kakarot deployed and the warped contracts. The test themselves should not be modified (apart from the `traceit.context` to report performances accordingly.

**Comment by ClementWalter** [comment]
just tried locally to warp our test suite but it doesn't work as the contracts use solidity features not supported by warp

```
$ warp transpile ./tests/integration/solidity_contracts/PlainOpcodes/PlainOpcodes.sol 
---Solc warnings:
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> tests/integration/solidity_contracts/PlainOpcodes/RevertTestCases.sol


---
Transpilation abandoned Detected 3 Unsupported Features:

File tests/integration/solidity_contracts/PlainOpcodes/PlainOpcodes.sol:

1. Solidity builtin blockhash is not supported:

        ................
42          //////////////////////////////////////////////////////////////*/
43          function opcodeBlockHash(
44              uint256 blockNumber
45          ) public view returns (bytes32 _blockhash) {
46              return (blockhash(blockNumber));
47          }
48
49          function opcodeAddress() public view returns (address selfAddress) {


2. Members of addresses are not supported. Found at MemberAccess #123:

        ................
55          }
56
57          function opcodeStaticCall2() public view returns (bool, bytes memory) {
58              bytes memory data = abi.encodeWithSelector(bytes4(keccak256("inc()")));
59              return address(counter).staticcall(data);
60          }
61
62          function opcodeCall() public {


3. Members of addresses are not supported. Found at MemberAccess #301:

        ................
135         
136         function testShouldRevertViaCall() external returns (bytes memory returnData) {
137             ContractRevertsOnMethodCall doomedContract = new ContractRevertsOnMethodCall();
138
139             (bool success, bytes memory returnData1) = address(doomedContract).call(abi.encodeWithSignature("triggerRevert()"));
140             address doomedContractCounter = address(doomedContract.counter());
141
142             assert(!success);
```

```
$ warp transpile ./tests/integration/solidity_contracts/PlainOpcodes/Caller.sol      
Transpilation abandoned Detected 1 Unsupported Features:

File tests/integration/solidity_contracts/PlainOpcodes/Caller.sol:

1. Members of addresses are not supported. Found at MemberAccess #17:

        ................
7           function call(
8               address target,
9               bytes calldata payload
10          ) external returns (bool success, bytes memory returnData) {
11              return address(target).call(payload);
12          }
13      }
```

```
$ warp transpile ./tests/integration/solidity_contracts/PlainOpcodes/RevertTestCases.sol 
---Solc warnings:
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> tests/integration/solidity_contracts/PlainOpcodes/RevertTestCases.sol


---
Running starknet compile with cairoPath /Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp
Traceback (most recent call last):
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/bin/starknet-compile", line 10, in <module>
    sys.exit(main())
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/starknet/compiler/compile.py", line 229, in main
    preprocessed = cairo_compile_common(
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/cairo_compile.py", line 116, in cairo_compile_common
    preprocessed = preprocess_codes(
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocess_codes.py", line 26, in preprocess_codes
    pass_manager.run(context)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/pass_manager.py", line 70, in run
    stage.run(context)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/default_pass_manager.py", line 105, in run
    preprocessor.visit(module)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/ast/visitor.py", line 42, in visit
    return getattr(self, f"visit_{type(obj).__name__}", self._visit_default)(obj)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 486, in visit_CairoModule
    super().visit_CairoModule(module)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/ast/visitor.py", line 69, in visit_CairoModule
    cairo_file=CairoFile(code_block=self.visit(module.cairo_file.code_block)),
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/ast/visitor.py", line 42, in visit
    return getattr(self, f"visit_{type(obj).__name__}", self._visit_default)(obj)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 474, in visit_CodeBlock
    self.visit_uncommented_code_block([x.code_elm for x in code_block.code_elements])
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 456, in visit_uncommented_code_block
    self.visit(elm)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/ast/visitor.py", line 42, in visit
    return getattr(self, f"visit_{type(obj).__name__}", self._visit_default)(obj)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/starknet/compiler/starknet_preprocessor.py", line 198, in visit_CodeElementFunction
    super().visit_CodeElementFunction(elm)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 675, in visit_CodeElementFunction
    self.visit_function_body_with_retries(
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 731, in visit_function_body_with_retries
    self.visit_uncommented_code_block(code_elements)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 456, in visit_uncommented_code_block
    self.visit(elm)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/ast/visitor.py", line 42, in visit
    return getattr(self, f"visit_{type(obj).__name__}", self._visit_default)(obj)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/starknet/compiler/starknet_preprocessor.py", line 198, in visit_CodeElementFunction
    super().visit_CodeElementFunction(elm)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 675, in visit_CodeElementFunction
    self.visit_function_body_with_retries(
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 737, in visit_function_body_with_retries
    self.visit_uncommented_code_block(code_elements)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 456, in visit_uncommented_code_block
    self.visit(elm)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/ast/visitor.py", line 42, in visit
    return getattr(self, f"visit_{type(obj).__name__}", self._visit_default)(obj)
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/cairo/lang/compiler/preprocessor/preprocessor.py", line 861, in visit_CodeElementWithAttr
    AttributeScope(
  File "<string>", line 9, in __init__
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/starkware_utils/validated_dataclass.py", line 25, in __post_init__
    self.validate_dataclass()
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/starkware_utils/validated_dataclass.py", line 28, in validate_dataclass
    self.validate_types()
  File "/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/warp_venv/lib/python3.9/site-packages/starkware/starkware_utils/validated_dataclass.py", line 124, in validate_types
    typeguard.check_type(
TypeError: check_type() got an unexpected keyword argument 'argname'
Compile failed
Unexpected error during transpilation
CLIError: Compilation of cairo file warp_output/tests/integration/solidity_contracts/PlainOpcodes/Counter.sol/Counter.cairo failed
    at computeClassHash (/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/postCairoWrite.js:111:15)
    at addClassHash (/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/postCairoWrite.js:96:21)
    at hashDependacies (/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/postCairoWrite.js:76:9)
    at /Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/postCairoWrite.js:65:9
    at Array.forEach (<anonymous>)
    at postProcessCairoFile (/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/postCairoWrite.js:64:17)
    at /Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/build/cli.js:88:70
    at Array.map (<anonymous>)
    at Command.runTranspile (/Users/clementwalter/.config/yarn/global/node_modules/@nethermindeth/warp/build/cli.js:88:14)
    at Command.listener [as _actionHandler] (/Users/clementwalter/.config/yarn/global/node_modules/commander/lib/command.js:482:17)
    at /Users/clementwalter/.config/yarn/global/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/clementwalter/.config/yarn/global/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/clementwalter/.config/yarn/global/node_modules/commander/lib/command.js:1283:27)
    at /Users/clementwalter/.config/yarn/global/node_modules/commander/lib/command.js:1081:27
    at Command._chainOrCall (/Users/clementwalter/.config/yarn/global/node_modules/commander/lib/command.js:1177:12)
    at Command._dispatchSubcommand (/Users/clementwalter/.config/yarn/global/node_modules/commander/lib/command.js:1077:23)
Transpilation failed
```
